# https://github.com/deconz-community/deconz-docker
services:
  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    hostname: deconz
    restart: always
    ports: 
      - 80:80
      - 443:443
    volumes:
      - /opt/deconz:/opt/deCONZ
    devices:
#      - /dev/ttyUSB0
      - /dev/serial/by-id/${CONBEE}:/dev/ttyACM0
    environment:
      - TZ
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
