# basic version of experimental on github
# https://github.com/fhem/fhem-docker/pkgs/container/fhem-experimental
services:
  fhem:
    image: ghcr.io/fhem/fhem-experimental:dev
    container_name: fhem
    hostname: fhem
    restart: always
    ports:
      - "8083:8083"
      - "1883:1883"
    environment:
      - TZ=Europe/Berlin
      - LC_ALL
      - LANG
    volumes:
      - "./fhem/:/opt/fhem/"
