# basic version of experimental on github
# https://github.com/fhem/fhem-docker/pkgs/container/fhem-experimental
services:
  fhem:
    image: ghcr.io/fhem/fhem-experimental:dev
    restart: always
    ports:
      - "8083:8083"
      - "1883:1883"
    environment:
      - TZ=Europe/Berlin
#      - HOST_HOSTNAME=${HOST_HOSTNAME} # $(hostname)
    volumes:
      - "./fhem/:/opt/fhem/"
