# https://svrooij.io/sonos2mqtt/getting-started.html#run-sonos2mqtt-in-docker
services:
  sonos:
    environment:
#      SONOS2MQTT_DEVICE: ${SONOS2MQTT_DEVICE}
      - SONOS2MQTT_DEVICE
      - SONOS2MQTT_MQTT
      - SONOS_LISTENER_HOST
#      SONOS2MQTT_MQTT: ${SONOS2MQTT_MQTT}
#      SONOS_LISTENER_HOST: ${SONOS_LISTENER_HOST}
#      SONOS_TTS_ENDPOINT: https://github-tts-blue-book.svrooij.io/api/generate
      - TZ=Europe/Berlin
    image: svrooij/sonos2mqtt
    ports:
    - 6329:6329/tcp
    restart: unless-stopped
