# https://svrooij.io/sonos2mqtt/getting-started.html#run-sonos2mqtt-in-docker
services:
  sonos:
    image: svrooij/sonos2mqtt
    container_name: sonos
    hostname: sonos
    ports:
    - 6329:6329/tcp
    restart: unless-stopped
    environment:
      - SONOS2MQTT_DEVICE
      - SONOS2MQTT_MQTT
      - SONOS_LISTENER_HOST
#      SONOS_TTS_ENDPOINT: https://github-tts-blue-book.svrooij.io/api/generate
      - TZ
